# Configuration package for Pixora AI Agent
from .prompts import (
    AGENT_SYSTEM_PROMPT,
    SCENE_BREAKDOWN_WITH_IMAGES,
    SCENE_BREAKDOWN_NO_IMAGES,
    IMAGE_ANALYSIS_PROMPT,
    ENHANCED_INPUT_TEMPLATE
)

__all__ = [
    "AGENT_SYSTEM_PROMPT",
    "SCENE_BREAKDOWN_WITH_IMAGES", 
    "SCENE_BREAKDOWN_NO_IMAGES",
    "IMAGE_ANALYSIS_PROMPT",
    "ENHANCED_INPUT_TEMPLATE"
]

